### ISSUE TITLE
Record of converting pandablocks-ioc

### ISSUE THREAD

**Issue by evalott100** [PandABlocks/fastcs-PandABlocks#3]
In conversion from pandablocks-ioc, certain records will change. I'll be documenting them here.

# TODO
## FastCS
- [ ] Add table structure datatype to FastCS.
- [ ] Add limits `DRVL` and `DRVH`to `Int` and `Float`.

## Panda
- [ ] Find the best structure for mimicking `INPA`.

**Comment by evalott100** [comment]
Names on `BITS` will no longer be `BITS:1:VAL` and `BITS:1:NAME`, instead `BITS:VAL1` and `BITS:NAME1`.

**Comment by evalott100** [comment]
Closing to document changes between pandablocks-ioc in https://github.com/PandABlocks/fastcs-PandABlocks/issues/8
